threads_num:                  30 #并行加速启动线程数

meshTopic:                    '/polyve/mesh'
edgeTopic:                    '/polyve/edge'
vertexTopic:                  '/polyve/vert'


pcdmapname:                   "Torus_big" 

inputdata:                    "shapes/Torus_big.obj" 



poly_params:                   [0.0,0.0, 0.0,   10,0,80]  #初始时刻平移与旋转(yaw,pitch,roll) 体素中心的平移则应该让体素中心为原点








selfmapresu:                0.05 #自身SDF地图的分辨率

box_x:    3.0 #相应改变mybox.obj的长宽高
box_y:    0.3 #相应改变mybox.obj的长宽高
box_z:    0.3 #相应改变mybox.obj的长宽高
# =============注意box的选择时必须相应改变mybox.obj的长宽高========================
# =============注意box的选择时必须相应改变mybox.obj的长宽高========================
enable_sweptvolume:         true
uavwithobstacle:            true
uavwithmap:                 true
torlerance:                 0.005 #合并可视化swept volume碰撞时间区间的容忍分辨率
momentum:                   0.0 #Nesterov Momentum Acceleration 0.3ok从 2786433878---->2341580910

eps:                            0.20

transparency:                   1.0 #可视化swept volume的透明度
t_min:                          0
t_max:                          2


use_objfile_as_body:            true

testRate:                     100.0



# ts:                           15.0 #一段轨迹的时间
ts:                           2.0 #一段轨迹的时间
##动力学=========================================
vehicleMass:                0.61
gravAcc:                    9.8
horizDrag:                  0.10
vertDrag:                   0.10
parasDrag:                  0.01
speedEps:                   0.0001


##地图设置=========================================

mapTopic:                     '/voxel_map'
dilateRadius:               0.5
voxelWidth:                 0.15 #改写无launch文件。MapBound尽量对称，第五位保持0，第六位才是Z的高度,改为与eps一致?????或者是倍数关系则考虑降采样查询等等
mapBound:                   [-25.0, 25.0, -25.0, 25.0, 0.0, 15.0]
occupancy_resolution:      1.0 #环境地图的分辨率与自身shapekernel分辨率一致
debug_output:              false #bool
sta_threshold:             1 #int

kernel_size:  13     #必须为奇数，一个kernel的bounding boxsize，乘以地图分辨率occupancy_resolution为kernel各轴的长度
kernel_max_pitch: 45  # 单位：度
kernel_max_roll:  45
kernel_ang_res:   9   # 分辨率

front_end_safeh:  0.0

# ======= backend part ======= #

enableearlyExit:            true  
debugpause:                 1        #debug的暂停时间

smoothingEps:               1.0e-2    # smoothL1
# integralIntervs:            16        
integralIntervs:            64 #便于parallel debug!!!!!!       
# integralIntervs:            16 #便于parallel debug!!!!!!       
relCostTol:                 1.0e-16 
relCostTolMidEnd:           1.0e-6 #给太小出shit 导致  //step step太小导致d*step与xp数量级差距太大，再减去xp有问题，见lbfgs 618行注解
# relCostTolMidEnd:           1.0e-16 #给太小出shit 导致  //step step太小导致d*step与xp数量级差距太大，再减去xp有问题，见lbfgs 618行注解
vmax:                       1000
omgmax:                     1000
thetamax:                   10000.0

weight_v:                   1000.0       #work3版本1000参数
weight_a:                   1000.0       #work3版本1000参数
# weight_p:                   5000.0      #work3版本100 参数
weight_p:                   4000.0      #work3版本100 参数
weight_pr:                  1000.0       #work3版本100 参数
weight_ar:                  32000.0      #根据final cost的数量级调整的
weight_omg:                 1000.0       #work3版本100 参数
weight_theta:               1000.0       #work3版本100 参数
rho_mid_end:                200
rho:                        380        #离散地图版本
# rho:                        200           #work3版本20参数

# safety_hor:                 0.866     #work3版本1参数
safety_hor:                 0.866    #work3版本1参数
# safety_hor:                 0.900    #work3版本1参数
# safety_hor:                 1.5     #work3版本1参数
inittime:                   2.5 ###minco每段时间初始时间初始数值#work3版本10.0参数

mem_size:                   16 # The default value is 8. Values less than 3 are not recommended. Large values will result in excessive computing time.
past:                       10 #Distance for delta-based convergence test. This parameter determines the distance, in iterations, to compute the rate of decrease of the cost function
min_step:                   1.0e-32 #The minimum step of the line search routine.The default value is 1.0e-20. This value need not be modified unless the exponents are too large for the machine being used, or unless the problem is extremely badly scaled (in which case the exponents should be increased).
g_epsilon:                  0.0 #The default value is 1.0e-5.This should be greater than 1.0e-6 in practice because L-BFGS does not directly reduce first-order residual.
# relCostTol:                 1.0e-7 #The default value is 1.0e-6.Delta for convergence test.This parameter determines the minimum rate of decrease of the cost function


# ===============================可变形机器人只需新增Scale的三轴独立轨迹即可先在可视化中弄出来再求sdf场
